// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pb/payments.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PENDING  PaymentStatus = 0
	PaymentStatus_APPROVED PaymentStatus = 1
	PaymentStatus_DECLINED PaymentStatus = 2
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "DECLINED",
	}
	PaymentStatus_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"DECLINED": 2,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_pb_payments_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_payments_proto_rawDescGZIP(), []int{0}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payments.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_pb_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_pb_payments_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

type ProcessPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MetodoPagoToken string                 `protobuf:"bytes,4,opt,name=metodo_pago_token,json=metodoPagoToken,proto3" json:"metodo_pago_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_pb_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_pb_payments_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetMetodoPagoToken() string {
	if x != nil {
		return x.MetodoPagoToken
	}
	return ""
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payments.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_pb_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_pb_payments_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessPaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

type GetPaymentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderRequest) Reset() {
	*x = GetPaymentByOrderRequest{}
	mi := &file_pb_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderRequest) ProtoMessage() {}

func (x *GetPaymentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetPaymentByOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payments.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderResponse) Reset() {
	*x = GetPaymentByOrderResponse{}
	mi := &file_pb_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderResponse) ProtoMessage() {}

func (x *GetPaymentByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_payments_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentByOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPaymentByOrderResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPaymentByOrderResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

var File_pb_payments_proto protoreflect.FileDescriptor

const file_pb_payments_proto_rawDesc = "" +
	"\n" +
	"\x11pb/payments.proto\x12\bpayments\"\x96\x01\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.payments.PaymentStatusR\x06status\"\x8f\x01\n" +
	"\x15ProcessPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12*\n" +
	"\x11metodo_pago_token\x18\x04 \x01(\tR\x0fmetodoPagoToken\"Y\n" +
	"\x16ProcessPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.payments.PaymentStatusR\x06status\"5\n" +
	"\x18GetPaymentByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"t\n" +
	"\x19GetPaymentByOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.payments.PaymentStatusR\x06status*8\n" +
	"\rPaymentStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bDECLINED\x10\x022\xc4\x01\n" +
	"\x0fPaymentsService\x12S\n" +
	"\x0eProcessPayment\x12\x1f.payments.ProcessPaymentRequest\x1a .payments.ProcessPaymentResponse\x12\\\n" +
	"\x11GetPaymentByOrder\x12\".payments.GetPaymentByOrderRequest\x1a#.payments.GetPaymentByOrderResponseB+Z)github.com/gonzalo-fch/PaymentsService/pbb\x06proto3"

var (
	file_pb_payments_proto_rawDescOnce sync.Once
	file_pb_payments_proto_rawDescData []byte
)

func file_pb_payments_proto_rawDescGZIP() []byte {
	file_pb_payments_proto_rawDescOnce.Do(func() {
		file_pb_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_payments_proto_rawDesc), len(file_pb_payments_proto_rawDesc)))
	})
	return file_pb_payments_proto_rawDescData
}

var file_pb_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_payments_proto_goTypes = []any{
	(PaymentStatus)(0),                // 0: payments.PaymentStatus
	(*Payment)(nil),                   // 1: payments.Payment
	(*ProcessPaymentRequest)(nil),     // 2: payments.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),    // 3: payments.ProcessPaymentResponse
	(*GetPaymentByOrderRequest)(nil),  // 4: payments.GetPaymentByOrderRequest
	(*GetPaymentByOrderResponse)(nil), // 5: payments.GetPaymentByOrderResponse
}
var file_pb_payments_proto_depIdxs = []int32{
	0, // 0: payments.Payment.status:type_name -> payments.PaymentStatus
	0, // 1: payments.ProcessPaymentResponse.status:type_name -> payments.PaymentStatus
	0, // 2: payments.GetPaymentByOrderResponse.status:type_name -> payments.PaymentStatus
	2, // 3: payments.PaymentsService.ProcessPayment:input_type -> payments.ProcessPaymentRequest
	4, // 4: payments.PaymentsService.GetPaymentByOrder:input_type -> payments.GetPaymentByOrderRequest
	3, // 5: payments.PaymentsService.ProcessPayment:output_type -> payments.ProcessPaymentResponse
	5, // 6: payments.PaymentsService.GetPaymentByOrder:output_type -> payments.GetPaymentByOrderResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_payments_proto_init() }
func file_pb_payments_proto_init() {
	if File_pb_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_payments_proto_rawDesc), len(file_pb_payments_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_payments_proto_goTypes,
		DependencyIndexes: file_pb_payments_proto_depIdxs,
		EnumInfos:         file_pb_payments_proto_enumTypes,
		MessageInfos:      file_pb_payments_proto_msgTypes,
	}.Build()
	File_pb_payments_proto = out.File
	file_pb_payments_proto_goTypes = nil
	file_pb_payments_proto_depIdxs = nil
}
