// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order-service/catalogpb/catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListComerciosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoloActivos   bool                   `protobuf:"varint,1,opt,name=solo_activos,json=soloActivos,proto3" json:"solo_activos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComerciosRequest) Reset() {
	*x = ListComerciosRequest{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComerciosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComerciosRequest) ProtoMessage() {}

func (x *ListComerciosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComerciosRequest.ProtoReflect.Descriptor instead.
func (*ListComerciosRequest) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ListComerciosRequest) GetSoloActivos() bool {
	if x != nil {
		return x.SoloActivos
	}
	return false
}

type ListComerciosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comercios     []*Comercio            `protobuf:"bytes,1,rep,name=comercios,proto3" json:"comercios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComerciosResponse) Reset() {
	*x = ListComerciosResponse{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComerciosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComerciosResponse) ProtoMessage() {}

func (x *ListComerciosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComerciosResponse.ProtoReflect.Descriptor instead.
func (*ListComerciosResponse) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListComerciosResponse) GetComercios() []*Comercio {
	if x != nil {
		return x.Comercios
	}
	return nil
}

type Comercio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Direccion     string                 `protobuf:"bytes,3,opt,name=direccion,proto3" json:"direccion,omitempty"`
	Activo        bool                   `protobuf:"varint,4,opt,name=activo,proto3" json:"activo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comercio) Reset() {
	*x = Comercio{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comercio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comercio) ProtoMessage() {}

func (x *Comercio) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comercio.ProtoReflect.Descriptor instead.
func (*Comercio) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Comercio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comercio) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Comercio) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

func (x *Comercio) GetActivo() bool {
	if x != nil {
		return x.Activo
	}
	return false
}

type GetMenuByComercioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComercioId    string                 `protobuf:"bytes,1,opt,name=comercio_id,json=comercioId,proto3" json:"comercio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuByComercioRequest) Reset() {
	*x = GetMenuByComercioRequest{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuByComercioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuByComercioRequest) ProtoMessage() {}

func (x *GetMenuByComercioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuByComercioRequest.ProtoReflect.Descriptor instead.
func (*GetMenuByComercioRequest) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuByComercioRequest) GetComercioId() string {
	if x != nil {
		return x.ComercioId
	}
	return ""
}

type GetMenuByComercioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Productos     []*Product             `protobuf:"bytes,1,rep,name=productos,proto3" json:"productos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuByComercioResponse) Reset() {
	*x = GetMenuByComercioResponse{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuByComercioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuByComercioResponse) ProtoMessage() {}

func (x *GetMenuByComercioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuByComercioResponse.ProtoReflect.Descriptor instead.
func (*GetMenuByComercioResponse) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuByComercioResponse) GetProductos() []*Product {
	if x != nil {
		return x.Productos
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Precio        float64                `protobuf:"fixed64,3,opt,name=precio,proto3" json:"precio,omitempty"`
	ComercioId    string                 `protobuf:"bytes,4,opt,name=comercio_id,json=comercioId,proto3" json:"comercio_id,omitempty"`
	Disponible    bool                   `protobuf:"varint,5,opt,name=disponible,proto3" json:"disponible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Product) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Product) GetComercioId() string {
	if x != nil {
		return x.ComercioId
	}
	return ""
}

func (x *Product) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

type GetProductDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailsRequest) Reset() {
	*x = GetProductDetailsRequest{}
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailsRequest) ProtoMessage() {}

func (x *GetProductDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_catalogpb_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailsRequest) Descriptor() ([]byte, []int) {
	return file_order_service_catalogpb_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_order_service_catalogpb_catalog_proto protoreflect.FileDescriptor

const file_order_service_catalogpb_catalog_proto_rawDesc = "" +
	"\n" +
	"%order-service/catalogpb/catalog.proto\x12\acatalog\"9\n" +
	"\x14ListComerciosRequest\x12!\n" +
	"\fsolo_activos\x18\x01 \x01(\bR\vsoloActivos\"H\n" +
	"\x15ListComerciosResponse\x12/\n" +
	"\tcomercios\x18\x01 \x03(\v2\x11.catalog.ComercioR\tcomercios\"h\n" +
	"\bComercio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tdireccion\x18\x03 \x01(\tR\tdireccion\x12\x16\n" +
	"\x06activo\x18\x04 \x01(\bR\x06activo\";\n" +
	"\x18GetMenuByComercioRequest\x12\x1f\n" +
	"\vcomercio_id\x18\x01 \x01(\tR\n" +
	"comercioId\"K\n" +
	"\x19GetMenuByComercioResponse\x12.\n" +
	"\tproductos\x18\x01 \x03(\v2\x10.catalog.ProductR\tproductos\"\x8a\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06precio\x18\x03 \x01(\x01R\x06precio\x12\x1f\n" +
	"\vcomercio_id\x18\x04 \x01(\tR\n" +
	"comercioId\x12\x1e\n" +
	"\n" +
	"disponible\x18\x05 \x01(\bR\n" +
	"disponible\"*\n" +
	"\x18GetProductDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x86\x02\n" +
	"\x0eCatalogService\x12N\n" +
	"\rListComercios\x12\x1d.catalog.ListComerciosRequest\x1a\x1e.catalog.ListComerciosResponse\x12Z\n" +
	"\x11GetMenuByComercio\x12!.catalog.GetMenuByComercioRequest\x1a\".catalog.GetMenuByComercioResponse\x12H\n" +
	"\x11GetProductDetails\x12!.catalog.GetProductDetailsRequest\x1a\x10.catalog.ProductB%Z#foodrush/orders/catalogpb;catalogpbb\x06proto3"

var (
	file_order_service_catalogpb_catalog_proto_rawDescOnce sync.Once
	file_order_service_catalogpb_catalog_proto_rawDescData []byte
)

func file_order_service_catalogpb_catalog_proto_rawDescGZIP() []byte {
	file_order_service_catalogpb_catalog_proto_rawDescOnce.Do(func() {
		file_order_service_catalogpb_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_catalogpb_catalog_proto_rawDesc), len(file_order_service_catalogpb_catalog_proto_rawDesc)))
	})
	return file_order_service_catalogpb_catalog_proto_rawDescData
}

var file_order_service_catalogpb_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_service_catalogpb_catalog_proto_goTypes = []any{
	(*ListComerciosRequest)(nil),      // 0: catalog.ListComerciosRequest
	(*ListComerciosResponse)(nil),     // 1: catalog.ListComerciosResponse
	(*Comercio)(nil),                  // 2: catalog.Comercio
	(*GetMenuByComercioRequest)(nil),  // 3: catalog.GetMenuByComercioRequest
	(*GetMenuByComercioResponse)(nil), // 4: catalog.GetMenuByComercioResponse
	(*Product)(nil),                   // 5: catalog.Product
	(*GetProductDetailsRequest)(nil),  // 6: catalog.GetProductDetailsRequest
}
var file_order_service_catalogpb_catalog_proto_depIdxs = []int32{
	2, // 0: catalog.ListComerciosResponse.comercios:type_name -> catalog.Comercio
	5, // 1: catalog.GetMenuByComercioResponse.productos:type_name -> catalog.Product
	0, // 2: catalog.CatalogService.ListComercios:input_type -> catalog.ListComerciosRequest
	3, // 3: catalog.CatalogService.GetMenuByComercio:input_type -> catalog.GetMenuByComercioRequest
	6, // 4: catalog.CatalogService.GetProductDetails:input_type -> catalog.GetProductDetailsRequest
	1, // 5: catalog.CatalogService.ListComercios:output_type -> catalog.ListComerciosResponse
	4, // 6: catalog.CatalogService.GetMenuByComercio:output_type -> catalog.GetMenuByComercioResponse
	5, // 7: catalog.CatalogService.GetProductDetails:output_type -> catalog.Product
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_service_catalogpb_catalog_proto_init() }
func file_order_service_catalogpb_catalog_proto_init() {
	if File_order_service_catalogpb_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_catalogpb_catalog_proto_rawDesc), len(file_order_service_catalogpb_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_catalogpb_catalog_proto_goTypes,
		DependencyIndexes: file_order_service_catalogpb_catalog_proto_depIdxs,
		MessageInfos:      file_order_service_catalogpb_catalog_proto_msgTypes,
	}.Build()
	File_order_service_catalogpb_catalog_proto = out.File
	file_order_service_catalogpb_catalog_proto_goTypes = nil
	file_order_service_catalogpb_catalog_proto_depIdxs = nil
}
