// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: catalogpb/catalog.proto

package catalogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_ListComercios_FullMethodName     = "/catalog.CatalogService/ListComercios"
	CatalogService_GetMenuByComercio_FullMethodName = "/catalog.CatalogService/GetMenuByComercio"
	CatalogService_GetProductDetails_FullMethodName = "/catalog.CatalogService/GetProductDetails"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	ListComercios(ctx context.Context, in *ListComerciosRequest, opts ...grpc.CallOption) (*ListComerciosResponse, error)
	GetMenuByComercio(ctx context.Context, in *GetMenuByComercioRequest, opts ...grpc.CallOption) (*GetMenuByComercioResponse, error)
	GetProductDetails(ctx context.Context, in *GetProductDetailsRequest, opts ...grpc.CallOption) (*Product, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ListComercios(ctx context.Context, in *ListComerciosRequest, opts ...grpc.CallOption) (*ListComerciosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListComerciosResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListComercios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetMenuByComercio(ctx context.Context, in *GetMenuByComercioRequest, opts ...grpc.CallOption) (*GetMenuByComercioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuByComercioResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetMenuByComercio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProductDetails(ctx context.Context, in *GetProductDetailsRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, CatalogService_GetProductDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	ListComercios(context.Context, *ListComerciosRequest) (*ListComerciosResponse, error)
	GetMenuByComercio(context.Context, *GetMenuByComercioRequest) (*GetMenuByComercioResponse, error)
	GetProductDetails(context.Context, *GetProductDetailsRequest) (*Product, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) ListComercios(context.Context, *ListComerciosRequest) (*ListComerciosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComercios not implemented")
}
func (UnimplementedCatalogServiceServer) GetMenuByComercio(context.Context, *GetMenuByComercioRequest) (*GetMenuByComercioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenuByComercio not implemented")
}
func (UnimplementedCatalogServiceServer) GetProductDetails(context.Context, *GetProductDetailsRequest) (*Product, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductDetails not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ListComercios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListComerciosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListComercios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListComercios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListComercios(ctx, req.(*ListComerciosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetMenuByComercio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuByComercioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetMenuByComercio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetMenuByComercio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetMenuByComercio(ctx, req.(*GetMenuByComercioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProductDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProductDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProductDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProductDetails(ctx, req.(*GetProductDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComercios",
			Handler:    _CatalogService_ListComercios_Handler,
		},
		{
			MethodName: "GetMenuByComercio",
			Handler:    _CatalogService_GetMenuByComercio_Handler,
		},
		{
			MethodName: "GetProductDetails",
			Handler:    _CatalogService_GetProductDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalogpb/catalog.proto",
}
