version: '3.8'

services:
  postgresql-user:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql-user-data:/var/lib/postgresql/data
      - ./user-service/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_admin -d user_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: foodrush-user-service:local
    restart: unless-stopped
    environment:
      DB_HOST: postgresql-user
      DB_PORT: 5432
      DB_USER: user_admin
      DB_PASSWORD: user_password
      DB_NAME: user_db
      DB_SSLMODE: disable
      GRPC_PORT: 50051
    depends_on:
      postgresql-user:
        condition: service_healthy
    ports:
      - "50051:50051"

  catalog-service:
    build: ./catalog-service
    container_name: foodrush_catalog
    restart: on-failure
    depends_on:
      postgresql-catalog:
        condition: service_healthy
    ports:
      - "50052:50052"
    environment:
      DB_URL: user=postgres password=admin123 host=postgresql-catalog port=5432 dbname=foodrush_db sslmode=disable

  postgresql-catalog:
    image: postgres:16-alpine
    container_name: foodrush_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: foodrush_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./catalog-service/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d foodrush_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  orders-service:
    build: ./order-service
    ports:
      - "50053:50053"
    environment:
      - MONGO_URI=mongodb://mongodb-orders:27017
      - PORT=50053
    depends_on:
      - mongodb-orders

  mongodb-orders:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgresql-user-data:
  postgres_data:
  mongodb_data:
