// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/orders.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductoId    string                 `protobuf:"bytes,1,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Cantidad      int32                  `protobuf:"varint,2,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *OrderItem) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ComercioId     string                 `protobuf:"bytes,3,opt,name=comercio_id,json=comercioId,proto3" json:"comercio_id,omitempty"`
	Items          []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Total          float64                `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	QrRetiro       string                 `protobuf:"bytes,7,opt,name=qr_retiro,json=qrRetiro,proto3" json:"qr_retiro,omitempty"`
	ComprobanteUrl string                 `protobuf:"bytes,8,opt,name=comprobante_url,json=comprobanteUrl,proto3" json:"comprobante_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetComercioId() string {
	if x != nil {
		return x.ComercioId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetQrRetiro() string {
	if x != nil {
		return x.QrRetiro
	}
	return ""
}

func (x *Order) GetComprobanteUrl() string {
	if x != nil {
		return x.ComprobanteUrl
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ComercioId    string                 `protobuf:"bytes,2,opt,name=comercio_id,json=comercioId,proto3" json:"comercio_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetComercioId() string {
	if x != nil {
		return x.ComercioId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Ejemplo: "CREATED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CreateOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOrderDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailsRequest) Reset() {
	*x = GetOrderDetailsRequest{}
	mi := &file_proto_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsRequest) ProtoMessage() {}

func (x *GetOrderDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmOrderPickupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrRetiro      string                 `protobuf:"bytes,1,opt,name=qr_retiro,json=qrRetiro,proto3" json:"qr_retiro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOrderPickupRequest) Reset() {
	*x = ConfirmOrderPickupRequest{}
	mi := &file_proto_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOrderPickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderPickupRequest) ProtoMessage() {}

func (x *ConfirmOrderPickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderPickupRequest.ProtoReflect.Descriptor instead.
func (*ConfirmOrderPickupRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmOrderPickupRequest) GetQrRetiro() string {
	if x != nil {
		return x.QrRetiro
	}
	return ""
}

type ConfirmOrderPickupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NuevoStatus   string                 `protobuf:"bytes,2,opt,name=nuevo_status,json=nuevoStatus,proto3" json:"nuevo_status,omitempty"` // Ejemplo: "DELIVERED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmOrderPickupResponse) Reset() {
	*x = ConfirmOrderPickupResponse{}
	mi := &file_proto_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmOrderPickupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmOrderPickupResponse) ProtoMessage() {}

func (x *ConfirmOrderPickupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmOrderPickupResponse.ProtoReflect.Descriptor instead.
func (*ConfirmOrderPickupResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmOrderPickupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmOrderPickupResponse) GetNuevoStatus() string {
	if x != nil {
		return x.NuevoStatus
	}
	return ""
}

var File_proto_orders_proto protoreflect.FileDescriptor

const file_proto_orders_proto_rawDesc = "" +
	"\n" +
	"\x12proto/orders.proto\x12\x06orders\"H\n" +
	"\tOrderItem\x12\x1f\n" +
	"\vproducto_id\x18\x01 \x01(\tR\n" +
	"productoId\x12\x1a\n" +
	"\bcantidad\x18\x02 \x01(\x05R\bcantidad\"\xee\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcomercio_id\x18\x03 \x01(\tR\n" +
	"comercioId\x12'\n" +
	"\x05items\x18\x04 \x03(\v2\x11.orders.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tqr_retiro\x18\a \x01(\tR\bqrRetiro\x12'\n" +
	"\x0fcomprobante_url\x18\b \x01(\tR\x0ecomprobanteUrl\"w\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcomercio_id\x18\x02 \x01(\tR\n" +
	"comercioId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.orders.OrderItemR\x05items\"S\n" +
	"\x13CreateOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"(\n" +
	"\x16GetOrderDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x19ConfirmOrderPickupRequest\x12\x1b\n" +
	"\tqr_retiro\x18\x01 \x01(\tR\bqrRetiro\"O\n" +
	"\x1aConfirmOrderPickupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fnuevo_status\x18\x02 \x01(\tR\vnuevoStatus2\xf5\x01\n" +
	"\fOrderService\x12F\n" +
	"\vCreateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x1b.orders.CreateOrderResponse\x12@\n" +
	"\x0fGetOrderDetails\x12\x1e.orders.GetOrderDetailsRequest\x1a\r.orders.Order\x12[\n" +
	"\x12ConfirmOrderPickup\x12!.orders.ConfirmOrderPickupRequest\x1a\".orders.ConfirmOrderPickupResponseB\x17Z\x15foodrush/orders/protob\x06proto3"

var (
	file_proto_orders_proto_rawDescOnce sync.Once
	file_proto_orders_proto_rawDescData []byte
)

func file_proto_orders_proto_rawDescGZIP() []byte {
	file_proto_orders_proto_rawDescOnce.Do(func() {
		file_proto_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orders_proto_rawDesc), len(file_proto_orders_proto_rawDesc)))
	})
	return file_proto_orders_proto_rawDescData
}

var file_proto_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orders_proto_goTypes = []any{
	(*OrderItem)(nil),                  // 0: orders.OrderItem
	(*Order)(nil),                      // 1: orders.Order
	(*CreateOrderRequest)(nil),         // 2: orders.CreateOrderRequest
	(*CreateOrderResponse)(nil),        // 3: orders.CreateOrderResponse
	(*GetOrderDetailsRequest)(nil),     // 4: orders.GetOrderDetailsRequest
	(*ConfirmOrderPickupRequest)(nil),  // 5: orders.ConfirmOrderPickupRequest
	(*ConfirmOrderPickupResponse)(nil), // 6: orders.ConfirmOrderPickupResponse
}
var file_proto_orders_proto_depIdxs = []int32{
	0, // 0: orders.Order.items:type_name -> orders.OrderItem
	0, // 1: orders.CreateOrderRequest.items:type_name -> orders.OrderItem
	2, // 2: orders.OrderService.CreateOrder:input_type -> orders.CreateOrderRequest
	4, // 3: orders.OrderService.GetOrderDetails:input_type -> orders.GetOrderDetailsRequest
	5, // 4: orders.OrderService.ConfirmOrderPickup:input_type -> orders.ConfirmOrderPickupRequest
	3, // 5: orders.OrderService.CreateOrder:output_type -> orders.CreateOrderResponse
	1, // 6: orders.OrderService.GetOrderDetails:output_type -> orders.Order
	6, // 7: orders.OrderService.ConfirmOrderPickup:output_type -> orders.ConfirmOrderPickupResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_orders_proto_init() }
func file_proto_orders_proto_init() {
	if File_proto_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orders_proto_rawDesc), len(file_proto_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orders_proto_goTypes,
		DependencyIndexes: file_proto_orders_proto_depIdxs,
		MessageInfos:      file_proto_orders_proto_msgTypes,
	}.Build()
	File_proto_orders_proto = out.File
	file_proto_orders_proto_goTypes = nil
	file_proto_orders_proto_depIdxs = nil
}
