apiVersion: 1

groups:
  - orgId: 1
    name: foodrush-alerts
    folder: FoodRush
    interval: 20s
    rules:
      - uid: foodrush-error-rate
        title: Error rate alto
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              expr: |
                sum(rate(http_requests_total{status=~"5.."}[5m]))
                /
                sum(rate(http_requests_total[5m]))
              instant: true
          - refId: B
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params: [0.01]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: B
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: "Tasa de errores 5xx superior al 1% en los últimos 5 minutos"
        labels:
          severity: warning
